/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.covidnotfound;

import java.awt.Color;

/**
 *
 * @author alehen
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public TelaAdm() {
        super ("CovidNotFound - Administrador");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gerenciarAdmButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        gerenciarPacientesButton = new javax.swing.JButton();
        deslogarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        gerenciarAdmButton.setText("Cadastro e gerenciamento de ADMINISTRADORES/FUNCIONÁRIOS");
        gerenciarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarAdmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gerenciarAdmButton);
        gerenciarAdmButton.setBounds(170, 80, 470, 70);

        jButton2.setText("Gerar relatório");
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 300, 470, 70);

        gerenciarPacientesButton.setText("Cadastro e gerenciamento de PACIENTES");
        gerenciarPacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarPacientesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gerenciarPacientesButton);
        gerenciarPacientesButton.setBounds(170, 190, 470, 70);

        deslogarButton.setBackground(new java.awt.Color(219, 24, 90));
        deslogarButton.setText("Deslogar");
        deslogarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEffect(evt);
            }
        });
        deslogarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deslogarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deslogarButton);
        deslogarButton.setBounds(330, 440, 160, 70);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarAdmButtonActionPerformed
        TelaGerenciarAdm telagerenciaradm = new TelaGerenciarAdm();
        this.dispose();
        telagerenciaradm.setVisible(true);
    }//GEN-LAST:event_gerenciarAdmButtonActionPerformed

    private void deslogarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deslogarButtonActionPerformed
        TelaLogion telalogin = new TelaLogion();
        this.dispose();
        telalogin.setVisible(true);
    }//GEN-LAST:event_deslogarButtonActionPerformed

    private void mouseEffect(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEffect
        setBackground(Color.RED);
    }//GEN-LAST:event_mouseEffect

    private void gerenciarPacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarPacientesButtonActionPerformed
        TelaGerenciarPaciente telagerenciarpaciente = new TelaGerenciarPaciente();
        this.dispose();
        telagerenciarpaciente.setVisible(true);
    }//GEN-LAST:event_gerenciarPacientesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deslogarButton;
    private javax.swing.JButton gerenciarAdmButton;
    private javax.swing.JButton gerenciarPacientesButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
