/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.covidnotfound;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alehen
 */
public class TelaGerenciarAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciarAdm
     */
    public TelaGerenciarAdm() {
        super ("CovidNotFound - Gerenciamento de cadastro");
        initComponents();
        setLocationRelativeTo(null);
        buscarUsuarios();
    }
    
    private void buscarUsuarios(){
        try{
            DAO dao = new DAO();
            UsuarioGerenciar[] usuariogerenciar = dao.obterUsuarios();
            usuarioComboBox.setModel(new DefaultComboBoxModel<>(usuariogerenciar));
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, "Usuários não cadastrados, tente novamente mais tarde...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        usuarioComboBox = new javax.swing.JComboBox<>();
        idTextField = new javax.swing.JTextField();
        tipoTextField = new javax.swing.JTextField();
        loginTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        novoButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();
        cpfTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        usuarioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(usuarioComboBox);
        usuarioComboBox.setBounds(200, 30, 400, 50);

        idTextField.setEditable(false);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(idTextField);
        idTextField.setBounds(200, 110, 180, 50);

        tipoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(tipoTextField);
        tipoTextField.setBounds(420, 110, 180, 50);
        jPanel2.add(loginTextField);
        loginTextField.setBounds(200, 190, 180, 50);
        jPanel2.add(nomeTextField);
        nomeTextField.setBounds(200, 270, 400, 50);

        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });
        jPanel2.add(novoButton);
        novoButton.setBounds(220, 430, 140, 50);

        atualizarButton.setText("Atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(atualizarButton);
        atualizarButton.setBounds(440, 430, 140, 50);

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(removerButton);
        removerButton.setBounds(220, 500, 140, 50);

        cancelarButton.setText("Voltar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelarButton);
        cancelarButton.setBounds(440, 500, 140, 50);
        jPanel2.add(senhaPasswordField);
        senhaPasswordField.setBounds(420, 190, 180, 50);

        cpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(cpfTextField);
        cpfTextField.setBounds(200, 350, 400, 50);

        idLabel.setText("Id:");
        jPanel2.add(idLabel);
        idLabel.setBounds(200, 90, 16, 18);

        tipoLabel.setText("Tipo:");
        jPanel2.add(tipoLabel);
        tipoLabel.setBounds(420, 90, 34, 18);

        loginLabel.setText("Login:");
        jPanel2.add(loginLabel);
        loginLabel.setBounds(200, 170, 42, 18);

        senhaLabel.setText("Senha:");
        jPanel2.add(senhaLabel);
        senhaLabel.setBounds(420, 170, 47, 18);

        nomeLabel.setText("Nome:");
        jPanel2.add(nomeLabel);
        nomeLabel.setBounds(200, 250, 46, 18);

        cpfLabel.setText("Cpf:");
        jPanel2.add(cpfLabel);
        cpfLabel.setBounds(200, 330, 29, 18);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        TelaAdm telaadm = new TelaAdm();
        this.dispose();
        telaadm.setVisible(true);        
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        String tipoUsuario = tipoTextField.getText();
        String loginUsuario = loginTextField.getText();
        String senhaUsuario = senhaPasswordField.getText();
        String nomeUsuario = nomeTextField.getText();
        String cpfUsuario = cpfTextField.getText();
        
        if(nomeUsuario == null || nomeUsuario.length() <= 2
                || loginUsuario == null || loginUsuario.length() <= 3 || senhaUsuario == null || senhaUsuario.length() < 6
                || cpfUsuario.equals("00000000000") || cpfUsuario.equals("11111111111") || cpfUsuario.equals("22222222222") 
                || cpfUsuario.equals("33333333333") || cpfUsuario.equals("44444444444") || cpfUsuario.equals("55555555555") 
                ||cpfUsuario.equals("66666666666") || cpfUsuario.equals("77777777777") ||cpfUsuario.equals("88888888888") 
                || cpfUsuario.equals("99999999999") ||
                (cpfUsuario.length() != 11) || !tipoUsuario.equals("adm") && !tipoUsuario.equals("usr")){
            
            JOptionPane.showMessageDialog(null, "Verifique os campos e tente novamente...");
        }else{
            try{
                int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro de novo " + tipoUsuario + "?","Adicionar novo usuário", JOptionPane.YES_NO_OPTION);
                switch (escolha){
                    case JOptionPane.YES_OPTION:
                        UsuarioGerenciar usuariogerenciar = new UsuarioGerenciar(tipoUsuario, loginUsuario, senhaUsuario, nomeUsuario, cpfUsuario);
                        DAO dao = new DAO();
                        dao.inserirUsuario(usuariogerenciar);
                        JOptionPane.showMessageDialog(null, "Usuário inserido com sucesso!");
                        buscarUsuarios();
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "A inserção não será feita.");
                        break;
                }
            }
            catch (Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Sistema indisponível, tente novamente mais tarde...");
            }
        }  
    }//GEN-LAST:event_novoButtonActionPerformed

    private void cpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldActionPerformed

    private void usuarioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioComboBoxActionPerformed
        UsuarioGerenciar usuariogerenciar = (UsuarioGerenciar) usuarioComboBox.getSelectedItem();
        idTextField.setText(Integer.toString(usuariogerenciar.getId()));
        tipoTextField.setText(usuariogerenciar.getTipo());
        loginTextField.setText(usuariogerenciar.getLogin());
        senhaPasswordField.setText(usuariogerenciar.getSenha());
        nomeTextField.setText(usuariogerenciar.getNome());
        cpfTextField.setText(usuariogerenciar.getCpf());
        
    }//GEN-LAST:event_usuarioComboBoxActionPerformed

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        int id = Integer.parseInt(idTextField.getText());
        String tipo = tipoTextField.getText();
        String login = loginTextField.getText();
        String senha = senhaPasswordField.getText();
        String nome = nomeTextField.getText();
        String cpf = cpfTextField.getText();
        
        
        if(nome == null || nome.length() <= 2
                || login == null || login.length() <= 3 || senha == null || senha.length() < 6
                || cpf.equals("00000000000") || cpf.equals("11111111111") || cpf.equals("22222222222") 
                || cpf.equals("33333333333") || cpf.equals("44444444444") || cpf.equals("55555555555") 
                ||cpf.equals("66666666666") || cpf.equals("77777777777") ||cpf.equals("88888888888") 
                || cpf.equals("99999999999") ||
                (cpf.length() != 11)|| !tipo.equals("adm") && !tipo.equals("usr")){
            
            JOptionPane.showMessageDialog(null, "Verifique os campos e tente novamente...");
        }else{
            try{
                int escolha = JOptionPane.showConfirmDialog(null, "Deseja atualizar o usuário?", "Atualizar", JOptionPane.YES_NO_OPTION);
                switch (escolha){
                    case JOptionPane.YES_OPTION:
                        UsuarioGerenciar usuariogerenciar = new UsuarioGerenciar (id, tipo, login, senha, nome, cpf);
                        DAO dao = new DAO();
                        dao.atualizarUsuarios(usuariogerenciar);
                        JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso");
                        buscarUsuarios();
                        idTextField.setText("");
                        tipoTextField.setText("");
                        loginTextField.setText("");
                        senhaPasswordField.setText("");
                        nomeTextField.setText("");
                        cpfTextField.setText("");
                            break;
                    default:
                        JOptionPane.showMessageDialog(null, "O usuário não será atualizado.");
                            break;
                }
            }
            catch (Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Sistema indisponível, tente novamente mais tarde...");
            }
        }   
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja remover usuário?", "Remover", JOptionPane.YES_NO_OPTION);
        if (escolha == JOptionPane.YES_OPTION){
            try{
                int id = Integer.parseInt (idTextField.getText());
                UsuarioGerenciar usuariogerenciar = new UsuarioGerenciar(id);
                DAO dao = new DAO();
                dao.removerUsuarios(usuariogerenciar);
                JOptionPane.showMessageDialog(null, "Usuário removido com sucesso!");
                buscarUsuarios();
                idTextField.setText("");
                tipoTextField.setText("");
                loginTextField.setText("");
                senhaPasswordField.setText("");
                nomeTextField.setText("");
                cpfTextField.setText("");
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde...");
                e.printStackTrace();
            }
        }        
    }//GEN-LAST:event_removerButtonActionPerformed

    private void tipoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton novoButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoTextField;
    private javax.swing.JComboBox<UsuarioGerenciar> usuarioComboBox;
    // End of variables declaration//GEN-END:variables
}
