/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.covidnotfound;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author alehen
 */
public class TelaConfirmarVacinacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaConfirmarVacinacao
     */
    public TelaConfirmarVacinacao() {
        super ("Covid Not Found - Confirmar vacina");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        cpfTextField = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setLayout(null);
        background.add(cpfTextField);
        cpfTextField.setBounds(210, 220, 420, 70);

        cpfLabel.setText("Digite seu CPF:");
        background.add(cpfLabel);
        cpfLabel.setBounds(210, 200, 170, 18);

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });
        background.add(confirmarButton);
        confirmarButton.setBounds(490, 350, 140, 60);

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        background.add(voltarButton);
        voltarButton.setBounds(210, 350, 140, 60);

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        String cpf = cpfTextField.getText();
            if(cpf == null || cpf.length() == 0){
                JOptionPane.showMessageDialog(null, "Por favor, preencha o cpf.");
            }
            else{
                try{
                    int escolha = JOptionPane.showConfirmDialog(null, "Confirmar registro?", "Registrar", JOptionPane.YES_NO_OPTION);
                    if(escolha == JOptionPane.YES_OPTION){
                        Pessoa p = new Pessoa(cpf);
                        DAO dao = new DAO();
                        if(dao.verificarCPFPes(p)){
                            Date d = new Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
                            String s = sdf.format(d);
                            p.setVacinacao(s);
                            dao.adicionarData(p);
                            JOptionPane.showMessageDialog(null, "Vacinação confirmada com sucesso");
                            cpfTextField.setText("");
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Pessoa Inválida");
                        }
                    }

                }
                catch (Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Falhou. Fale com o suporte.");
                }
            }
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        TelaUsuario telausuario = new TelaUsuario();
        this.dispose();
        telausuario.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmarVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmarVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmarVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmarVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfirmarVacinacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
